# Site settings
title:       The Berkeley Artificial Intelligence Research Blog
email:       bair-blog@berkeley.edu
author:      Daniel Seita
description: "The BAIR Blog"
baseurl:     ""
url:         "https://bairblog.github.io/"
date_format: "%b %-d, %Y"
timezone:    America/Los_Angeles

# Google services
google_analytics:
google_verification:

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    false
ajaxify_contact_form: false
future: true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: bair-blog

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number:

# Social icons
github_username:
bitbucket_username:
stackoverflow_id:
twitter_username:
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Spread the word: '
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: true
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: true

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     10
sass:
  compressed: true

# Plugins
# gems:         ['jekyll-paginate']
